---
name: Ruby Test

on:
  pull_request:

env:
  DATABASE_URL: postgres://postgres:password@127.0.0.1:5432

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ci_node_index:
          - 0
          - 1
    timeout-minutes: 30
    permissions:
      contents: read
      actions: read

    services:
      postgres:
        image: postgres:16.1-alpine3.19
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup ruby
        uses: ruby/setup-ruby@d697be2f83c6234b20877c3b5eac7a7f342f0d0c # v1.269.0
        with:
          bundler-cache: true

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: '.node-version'

      - name: Cache node modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: Run npm install
        run: |
          npm install --ignore-engines

      - name: Run rails db:setup
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:setup

      - name: Run rails assets:precompile
        run: |
          bin/rails assets:precompile

      - name: Download junit-xml-reports from artifact
        uses: dawidd6/action-download-artifact@0bd50d53a6d7fb5cb921e607957e9cc12b4ce392 # v12
        with:
          branch: main
          name: junit-xml-reports.*
          name_is_regexp: true
          path: tmp/junit-xml-reports-downloaded
        continue-on-error: true

      - name: Run split tests
        uses: r7kamura/split-tests-by-timings@5134247c551d8fe78ee44182a8228256e2ecd43e # v0.5.0
        id: split-tests
        with:
          reports: tmp/junit-xml-reports-downloaded
          glob: spec/**/*_spec.rb
          index: ${{ matrix.ci_node_index }}
          total: 2

      - name: Run rspec
        env:
          COVERAGE: true
        run: |
          bin/rspec \
            --format progress \
            --format RspecJunitFormatter \
            --out tmp/junit-xml-reports/junit-xml-report-${{ matrix.ci_node_index }}.xml \
            ${{ steps.split-tests.outputs.paths }}

      - name: Upload junit-xml-reports to artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: junit-xml-reports-${{ matrix.ci_node_index }}
          path: tmp/junit-xml-reports
          if-no-files-found: error

      - name: Rename coverage resultset file
        run: |
          if [ -f coverage/.resultset.json ]; then
            mv coverage/.resultset.json coverage/.resultset-test-${{ matrix.ci_node_index }}.json
          fi

      - name: Upload coverage-test-resultset file to artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: coverage-test-resultset-${{ matrix.ci_node_index }}
          path: coverage/.resultset-test-${{ matrix.ci_node_index }}.json
          if-no-files-found: error
          include-hidden-files: true

  coverage:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 5
    permissions:
      contents: read
      issues: write
      pull-requests: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup ruby
        uses: ruby/setup-ruby@d697be2f83c6234b20877c3b5eac7a7f342f0d0c # v1.269.0
        with:
          bundler-cache: true

      - name: Download coverage-test-resultset from artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          path: coverage
          pattern: coverage-test-resultset*
          merge-multiple: true

      - name: Run rails coverage:collate
        env:
          RAILS_ENV: test
        run: |
          bin/rails coverage:collate

      - name: Upload coverage to artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: coverage
          path: coverage
          if-no-files-found: error
          include-hidden-files: true

      - name: Report coverage to GitHub
        uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
        if: github.event_name == 'pull_request'
