---
name: Ruby Test

on:
  pull_request:

env:
  DATABASE_URL: postgres://postgres:password@127.0.0.1:5432

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ci_node_index:
          - 0
          - 1
    timeout-minutes: 30
    permissions:
      contents: read
      actions: read

    services:
      postgres:
        image: postgres:16.1-alpine3.19
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup ruby
        uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 # v1.254.0
        with:
          bundler-cache: true

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.node-version'

      - name: Cache node modules
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: Run npm install
        run: |
          npm install --ignore-engines

      - name: Run rails db:setup
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:setup

      - name: Run rails assets:precompile
        run: |
          bin/rails assets:precompile

      - name: Download junit-xml-reports from artifact
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          branch: main
          name: junit-xml-reports.*
          name_is_regexp: true
          path: tmp/junit-xml-reports-downloaded
        continue-on-error: true

      - name: Run split tests
        uses: r7kamura/split-tests-by-timings@4782de3f3298fdc4ffba75c670d175b749239ddf # v0.4.0
        id: split-tests
        with:
          reports: tmp/junit-xml-reports-downloaded
          glob: spec/**/*_spec.rb
          index: ${{ matrix.ci_node_index }}
          total: 2

      - name: Run rspec
        env:
          COVERAGE: true
        run: |
          bin/rspec \
            --format progress \
            --format RspecJunitFormatter \
            --out tmp/junit-xml-reports/junit-xml-report-${{ matrix.ci_node_index }}.xml \
            ${{ steps.split-tests.outputs.paths }}

      - name: Upload junit-xml-reports to artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: junit-xml-reports-${{ matrix.ci_node_index }}
          path: tmp/junit-xml-reports
          if-no-files-found: error

      - name: Rename coverage resultset file
        run: |
          if [ -f coverage/.resultset.json ]; then
            mv coverage/.resultset.json coverage/.resultset-test-${{ matrix.ci_node_index }}.json
          fi

      - name: Upload coverage-test-resultset file to artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-test-resultset-${{ matrix.ci_node_index }}
          path: coverage/.resultset-test-${{ matrix.ci_node_index }}.json
          if-no-files-found: error
          include-hidden-files: true

  coverage:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 5
    permissions:
      contents: read
      issues: write
      pull-requests: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup ruby
        uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 # v1.254.0
        with:
          bundler-cache: true

      - name: Download coverage-test-resultset from artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: coverage
          pattern: coverage-test-resultset*
          merge-multiple: true

      - name: Run rails coverage:collate
        env:
          RAILS_ENV: test
        run: |
          bin/rails coverage:collate

      - name: Upload coverage to artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage
          path: coverage
          if-no-files-found: error
          include-hidden-files: true

      - name: Report coverage to GitHub
        uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
        if: github.event_name == 'pull_request'
